server:
  port: 8081
spring:
  redis:
    # Redis服务器地址
    host: 39.96.175.246
    #Redis服务器连接端口
    port: 9000
    #password:
    # Redis数据库索引（默认为0）
    database: 1
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000